name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 19
        uses: actions/setup-node@v3
        with:
          node-version: 19.1.0

      - name: Install Railway
        working-directory: ./backend
        run: npm i -g @railway/cli

      - name: Deploy
        working-directory: ./backend
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}